stages:
        - containerise
        - verify

variables:
        GIT_STRATEGY: clone
        GIT_SUBMODULE_STRATEGY: recursive
        MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt
        DOCKER_TLS_CERTDIR: "/certs"
        DOCKER_DRIVER: overlay2
        CONTAINER: containers
        IMAGE: perfusion_and_tissue_damage

cache: &global_cache
        paths:
                - ${CONTAINER}/
        key: ${CI_COMMIT_REF_SLUG}
        policy: pull-push

.shared_hidden_key: &docker_definition
        image: docker:19.03.12
        services:
                - docker:19.03.12-dind

build_docker:
        <<: *docker_definition
        cache:
                <<: *global_cache
                policy: push
                key: docker
        stage: containerise
        script:
                - docker build -t ${IMAGE} ./
                - mkdir -p ${CONTAINER}
                - docker save ${IMAGE} > ${CONTAINER}/docker.tar

verify_docker:
        <<: *docker_definition
        cache:
                <<: *global_cache
                policy: pull
                key: docker
        stage: verify
        script:
                - docker load -i ${CONTAINER}/docker.tar
                - mkdir -p ${MOUNT_POINT}/docker
                - cp ./test_patient.yml ${MOUNT_POINT}/docker/patient.yml
                - docker run -v ${MOUNT_POINT}/docker:/patient ${IMAGE} /patient/patient.yml 1 test
                - docker run -v ${MOUNT_POINT}/docker:/patient ${IMAGE} /patient/patient.yml 2 test

build_singularity:
        <<: *docker_definition
        cache:
                <<: *global_cache
                policy: push
                key: singularity
        stage: containerise
        script:
                - sed -i 's/\.\/ \/app/\/app \/app/' singularity.def
                - mkdir -p ${MOUNT_POINT}
                - cp $(ls -p | grep -v /) ${MOUNT_POINT}/
                - cp -R in-silico-trial oxygen perfusion tissue_health ${MOUNT_POINT}/
                - docker run --privileged -v ${MOUNT_POINT}:/app quay.io/singularity/singularity:v3.6.2 build /app/${IMAGE}.sif /app/singularity.def
                - mkdir -p ${CONTAINER}
                - cp ${MOUNT_POINT}/${IMAGE}.sif ${CONTAINER}/singularity.sif

verify_singularity:
        <<: *docker_definition
        cache:
                <<: *global_cache
                policy: pull
                key: singularity
        stage: verify
        script:
                - mkdir -p ${MOUNT_POINT}/singularity
                - cp ./test_patient.yml ${MOUNT_POINT}/singularity/patient.yml
                - cp ${CONTAINER}/singularity.sif ${MOUNT_POINT}/${IMAGE}.sif
                - docker run --privileged -v ${MOUNT_POINT}:/patient quay.io/singularity/singularity:v3.6.2 run -B /patient/singularity:/patient /patient/${IMAGE}.sif /patient/patient.yml 1 test
                - docker run --privileged -v ${MOUNT_POINT}:/patient quay.io/singularity/singularity:v3.6.2 run -B /patient/singularity:/patient /patient/${IMAGE}.sif /patient/patient.yml 2 test
