input:
  # xdmf file refering to a tetrahedral mesh with labelled boundaries and subdomains
  mesh_file: '../brain_meshes/b0000/clustered.xdmf'
output:
  # folder for results
  res_fldr: '../brain_meshes/b0000/permeability/'
  # save sub-results
  save_subres: true
physical:
  # normal vector of the cortical surface in the reference coordinate system
  e_ref: [0, 0, 1]
  # arteriole/venule permeability tensor form [row1, row2, row3]
  K1_form: [0, 0, 0, 0, 0, 0, 0, 0, 1]